[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "/bin/sh /usr/local/bin/start.sh"
healthcheckPath = "/health"
healthcheckTimeout = 180
restartPolicyType = "ON_FAILURE"
